baseURL = "https://startaitools.com/"
title = "AI Solutions"
theme = "PaperMod"
[pagination]
pagerSize = 10

[params]
defaultTheme = "light"
ShowShareButtons = false
ShowReadingTime = false
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowWordCount = false
ShowRssButtonInSectionTermList = false
UseHugoToc = true
disableSpecial1stPost = true
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.homeInfoParams]
Title = "AI Implementation Services"
Content = "Deploy AI solutions in days, not months."

[[params.socialIcons]]
name = "github"
url = "https://github.com/jeremylongshore"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/jeremylongshore"

[[params.socialIcons]]
name = "email"
url = "mailto:jeremy@intentsolutions.io"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 10

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 20

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 30